42ForYou/backend

accounts/admin.py
accounts/apps.py
accounts/models.py
accounts/tests.py
accounts/views.py
pong/settings.py

User 모델을 추가했습니다.
- django app `accounts` 추가
- django model `User` 추가
django model은 app 내에 만들어야 하므로 `accounts` app을 먼저 추가했습니다. `users`로 이름짓지 않은 이유는 추후 프로필 정보 등 다른 모델이 추가될 수 있기 때문입니다.
django의 authorization은 내장된 `User` 모델로 이루어집니다. 이때 우리의 독자적인 `User` 모델을 만들어 보안/인증 작업에 사용할 수도 있지만 django의 내장된 기능을 최대한 활용할 수 있도록 구현하는 것이 낫다고 생각합니다(언제든 돌아갈 수 있으므로).
이를 위해 django의 `AbstractUser` 모델을 상속받아 `User` 모델을 구현했습니다.
```python
from django.db import models
from django.contrib.auth.models import AbstractUser
class User(AbstractUser):
intra_id = models.CharField(primary_key=True, max_length=32)
```
- `intra_id`: 추후 42OAuth 구현 시 사용될 필드이며 PK로 지정했습니다.
추가된 `User` 클래스를 django의 내장 인증 기능에 활용하기 위해서 `settings.py`에 아래 값을 지정했습니다.
```python
AUTH_USER_MODEL = "accounts.User"
```

FY-55 사용자 기본 모델 구현

---

requirements.txt
src/livechat/admin.py
src/livechat/apps.py
src/livechat/events.py
src/livechat/models.py
src/livechat/tests.py
src/livechat/views.py
src/livegame/admin.py
src/livegame/apps.py
src/livegame/events.py
src/livegame/models.py
src/livegame/tests.py
src/livegame/views.py
src/pong/asgi.py
src/pong/settings.py
src/socketcontrol/admin.py
src/socketcontrol/apps.py
src/socketcontrol/events.py
src/socketcontrol/models.py
src/socketcontrol/tests.py
src/socketcontrol/views.py

[FY-84](https://idealflower.atlassian.net/browse/FY-84)
- socketio 처리가 가능하게 세팅을 했습니다.
- 테스트를 통해 정상적으로 연결, 종료를 확인했습니다.
- livechat app 추가
- 채팅 관련 이벤트를 담당하는 app입니다.
- livegame
- game 관련 이벤트를 담당하는 app입니다.
- socketiocontrol
- 연결, 연결종료, 핑/퐁 등 기본적인 socketio 이벤트를 처리할 app입니다.
- [python-socketio](https://python-socketio.readthedocs.io/en/stable/server.html#defining-event-handlers)
- 해당 문서를 참고해서 socketio 이벤트를 작성합니다.
[FY-84]: https://idealflower.atlassian.net/browse/FY-84?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-84/socketio 세팅

---

src/game/models.py
src/game/serializers.py
src/game/views.py

[FY-82](https://idealflower.atlassian.net/browse/FY-82?atlOrigin=eyJpIjoiMTFiYTVjMDJlZWE3NGU5Njg4NTdjY2VhZjc4MWM1NWUiLCJwIjoiaiJ9)
- `GameResult` 및 `GameResultEntry` 모델 추가
- 위 모델에 대한 `ViewSet` 및 `Serializer` 추가
- `GameResult`의 경우 추후 상세 구현 필요
- 따라서 본 브랜치 삭제 불가
-   [ ] I read and included theses actions below
[FY-82]: https://idealflower.atlassian.net/browse/FY-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-82/feature/Game 결과 DB

---

src/authentication/urls.py
src/authentication/views.py
src/manage.py

[FY-113](https://idealflower.atlassian.net/ browse/FY-113)
- 프론트엔드의 사용자 토큰 유효성 검증을 위한 엔드포인트 생성 (/valid)
[FY-113]: https://idealflower.atlassian.net/browse/FY-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-113/vlidation Token end point

---

src/authentication/oauthviews.py
src/authentication/views.py
src/pong/settings.py

[FY-107](https://idealflower.atlassian.net/ browse)
- 이미 로그인 된 사용자 로그인 처리 set_cookies 추가
- 로그아웃에 인증 class 추가
[FY-107]: https://idealflower.atlassian.net/browse/FY-107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fy 107/프론트엔드 연결 에러 수정

---

src/game/views.py

- rebase중 충동해결과정에서 삭제된 코드르 다시 추가했습니다.

FY-97/Rebase중 삭제된 코드를 다시 추가했습니다.

---

src/pong/utils.py

[FY-111](https://idealflower.atlassian.net/browse/FY-111)
- CustomError 메세지가 올바른 json으로 응답하지않아 수정했습니다.
- dictg형태로 들어오는 에러메세지도 처리하게 수정했습니다
[FY-111]: https://idealflower.atlassian.net/browse/FY-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-111/CustomError error 메세지형태를 json으로 수정

---

src/game/views.py

- 단일 game_room get 요청에 현재 game에 속해있는 Players정보를 같이 전달합니다.

Fy-97/ add playsers when get single GameRoom

---

src/accounts/views.py
src/pong/settings.py

- avatar 이미지 저장폴더를 src와 같은 레벨로 변경했습니다.
- 이미지 저장경로를 .env에서 가져오도록 변경했습니다.

Fy-100/Change Profile image save folder

---

src/game/serializers.py
src/game/views.py
src/pong/settings.py

- Player 응답형식에 avatar추가
- Player 게임방 입장시 게임, 게임방, 참여 플레이어들 정보 제공으로 변경
- Player 게임방 입장불가 에러 메세지 구분 (진행중인 게임, 인원초과, 요청메세지오류)
- 단일 게임방 get요청이 game_room에 참가한 사람만 권한부여

Fy-97/GameRoom, Player API 업데이트

---

src/accounts/views.py

- 다른 사용자 응답 데이터에 자신과의 친구관계를 추가했습니다.
- "friend_status": "pending" or "friend" or"None"

FY-100/ 다른 사용자 조회 응답 데이터 업데이트

---

src/accounts/views.py

- avatar 파일이름 해쉬을 할 때 현재시간을 추가하여 같은 사용자이더라도 다른 파일이름을 저장하게 변경했습니다.

Fy-100/아바타 파일이름 해쉬에 현재시간 추가

---

src/game/views.py

- GameRoom 리스트 조회시 변화가 생긴 데이터가 끝으로 가는 동작이 있어서 "id"값을 기준으로 오름차순정렬을하여 보내줍니다.
- Player도 동일하게 오름차순정렬하여 제공합니다.

Fy-97/GameRoom, Player List 정렬

---

src/accounts/serializers.py
src/accounts/urls.py
src/accounts/views.py

[FY-136](https://idealflower.atlassian.net/browse/FY-136)
- 닉네임으로 유저조회가 가능한 API 개발
- 엔드포인트 "/api/accounts/search"
- 쿼리스트링 "?search={string}"
- "icontains"을 이용해서 대소문자 구분없이 쿼리스트링의 문자열이 포함된 모든 유저를 page단위로 제공합니다.
[FY-136]: https://idealflower.atlassian.net/browse/FY-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-136/유저 검색 API 개발

---

src/game/views.py

- game_room.status를 참조하던 코드를 is_playing을 참조하도록 변경했습니다.

FY-97/Fix: game_room.status to game_room.is_playing

---

src/game/views.py

- 게임룸 destory의 리턴값 변경
- 단일룸 GET json에 "my_player_id" 추가

FY-97/GameRoom DELET 에러 수정

---

src/game/views.py

- 유저가 하나의 게임방에만 참가가능하게 함수를 추가헸습니다.
- user를 가진 Player의 Game이 GameRoom을 가진상태이면  Player를 생성할 수 없습니다.

FY-97/하나의 게임방에만 참가가능하도록 업데이트

---

src/accounts/views.py

- 닉네임, 이메일 중복 발생시 Response raise를 CustomError로 변경

Fy-100/프로필 유효성검사 에러 리턴 수정

---

src/accounts/views.py
src/authentication/oauthviews.py
src/authentication/views.py
src/friends/serializers.py
src/pong/settings.py
src/pong/utils.py

[FY-149](https://idealflower.atlassian.net/browse/FY-149)
- 에러를 응답하는 코드를 정리하였습니다.
- 추가적으로 필요없는 코드를 일부 삭제
[FY-149]: https://idealflower.atlassian.net/browse/FY-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-149/에러 응답 코드 정리

---

src/accounts/views.py

- 프로필 응답 json에 친구상태이면 friend 모델의 id를 friend_id에 추가했습니다.

FY-100/Profile응답에 friend_id 값 추가

---

src/game/views.py

- 게임방 리스트 조회시 게임방에 있는 Player들의 정보도 같이 전달합니다.

Fy-97/게임방 리스트에 플레이어 정보 추가

---

src/pong/asgi.py
src/pong/settings.py

[FY-161](https://idealflower.atlassian.net/browse/FY-161)
- 소켓연결 요청시 CORS문제 해결
- 소켓 로그출력 추가
[FY-161]: https://idealflower.atlassian.net/browse/FY-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-161/CORS 에러 방지와 소켓 로깅을 추가했습니다.

---

src/accounts/views.py
src/friends/views.py
src/game/databaseio.py
src/game/views.py
src/pong/utils.py

[FY-159](https://idealflower.atlassian.net/browse/FY-159)
-   [x] I read and included theses actions below
- game_room_id를 받아 Json을 리턴하는 함수를 분리했습니다.
- from game.databaseio import get_single_game_room 으로 사용합니다.
```
{
"game": {
"game_id": 1,
"is_tournament": true,
"game_point": 10,
"time_limit": 10,
"n_players": 10
},
"room": {
"id": 1,
"title": "titlez",
"is_playing": false,
"join_players": 6,
"game": 1,
"host": "sanghwal3"
},
"players": [
{
"id": 1,
"avatar": "4b167961ce450e347220a84da8c1e64228b359f60c8528bff7559fb6e35cc33f.png",
"game": 1,
"nickname": "sanghwal3",
"rank": 0
},
{
"id": 3,
"avatar": "avatar_michael.jpg",
"game": 1,
"nickname": "nick_michael",
"rank": 0
}
]
}
```
my_player_id를 제외한 정보를 제공합니다.
[FY-159]: …

Fy-159/단일 게임룸 DB작업 함수 분리

---

src/game/databaseio.py
src/game/views.py

[FY-159](https://idealflower.atlassian.net/browse/FY-159)
-   [x] I read and included theses actions below
- get_single_game_room 응답 데이터 수정
[FY-159]: https://idealflower.atlassian.net/browse/FY-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-159/get_single_game_room 응답 수정

---

src/livegame/GameRoomSession.py

모든 게임이 종료된후 데이터를 DB에 저장하는 함수를 리팩토링했습니다.
- Game.users, SubGame, Player들을 저장합니다.
[FY-183](https://idealflower.atlassian.net/browse/FY-183)
-   [x] I read and included theses actions below
[FY-183]: https://idealflower.atlassian.net/browse/FY-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-183/게임결과 저장 함수 리팩토링

---

src/livegame/GameRoomSession.py
src/livegame/SubGameConfig.py
src/livegame/SubGameSession/SIOAdapter.py
src/livegame/SubGameSession/SubGameSession.py

[FY-166](https://idealflower.atlassian.net/browse/FY-166?atlOrigin=eyJpIjoiZTZmNGUzMTgzMjg1NDRhMDg3OTE1Mjg2MWE4ZTY0ZmIiLCJwIjoiaiJ9)
https://www.notion.so/silent42/c08bdff8ad8742e8b58be77e854f140a?pvs=4
https://www.notion.so/silent42/df4b426a5d4a49cfba641a879c50f106?pvs=4
-   [ ] I read and included theses actions below
[FY-166]: https://idealflower.atlassian.net/browse/FY-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FY-166/feature/socketio api 구현
